name: Unit Test Workflow

on:
  push:         # El trigger que dispara, en este caso, un push
    branches:
      - main    # Las ramas donde se ejecutar√° este workflow

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      TEST_ENV: true
    steps:
      - name: Configurar repositorio
        uses: actions/checkout@v3
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar pruebas
        run: pytest
